name: Test build docker images

on: [push, pull_request]

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        run: |
          apt-get install -y podman

      - name: Test to build docker images
        run: |
          podman build -t boost -f Dockerfile.ubuntu . && echo "Succeed!"
